import Head from "next/head";
import Image from "next/image";
import { Container } from "react-bootstrap";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Poke App | Abhi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <h1>Lets dev!</h1>
        </Container>
      </main>
    </div>
  );
}
